/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AgentAssignment } from "./AgentAssignment";
import { AgentAssignmentCountArgs } from "./AgentAssignmentCountArgs";
import { AgentAssignmentFindManyArgs } from "./AgentAssignmentFindManyArgs";
import { AgentAssignmentFindUniqueArgs } from "./AgentAssignmentFindUniqueArgs";
import { CreateAgentAssignmentArgs } from "./CreateAgentAssignmentArgs";
import { UpdateAgentAssignmentArgs } from "./UpdateAgentAssignmentArgs";
import { DeleteAgentAssignmentArgs } from "./DeleteAgentAssignmentArgs";
import { Client } from "../../client/base/Client";
import { Property } from "../../property/base/Property";
import { AgentAssignmentService } from "../agentAssignment.service";
@graphql.Resolver(() => AgentAssignment)
export class AgentAssignmentResolverBase {
  constructor(protected readonly service: AgentAssignmentService) {}

  async _agentAssignmentsMeta(
    @graphql.Args() args: AgentAssignmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AgentAssignment])
  async agentAssignments(
    @graphql.Args() args: AgentAssignmentFindManyArgs
  ): Promise<AgentAssignment[]> {
    return this.service.agentAssignments(args);
  }

  @graphql.Query(() => AgentAssignment, { nullable: true })
  async agentAssignment(
    @graphql.Args() args: AgentAssignmentFindUniqueArgs
  ): Promise<AgentAssignment | null> {
    const result = await this.service.agentAssignment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AgentAssignment)
  async createAgentAssignment(
    @graphql.Args() args: CreateAgentAssignmentArgs
  ): Promise<AgentAssignment> {
    return await this.service.createAgentAssignment({
      ...args,
      data: {
        ...args.data,

        client: args.data.client
          ? {
              connect: args.data.client,
            }
          : undefined,

        property: args.data.property
          ? {
              connect: args.data.property,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => AgentAssignment)
  async updateAgentAssignment(
    @graphql.Args() args: UpdateAgentAssignmentArgs
  ): Promise<AgentAssignment | null> {
    try {
      return await this.service.updateAgentAssignment({
        ...args,
        data: {
          ...args.data,

          client: args.data.client
            ? {
                connect: args.data.client,
              }
            : undefined,

          property: args.data.property
            ? {
                connect: args.data.property,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AgentAssignment)
  async deleteAgentAssignment(
    @graphql.Args() args: DeleteAgentAssignmentArgs
  ): Promise<AgentAssignment | null> {
    try {
      return await this.service.deleteAgentAssignment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Client, {
    nullable: true,
    name: "client",
  })
  async getClient(
    @graphql.Parent() parent: AgentAssignment
  ): Promise<Client | null> {
    const result = await this.service.getClient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Property, {
    nullable: true,
    name: "property",
  })
  async getProperty(
    @graphql.Parent() parent: AgentAssignment
  ): Promise<Property | null> {
    const result = await this.service.getProperty(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
